version: "3.9"

services:
  kb-suite:
    image: ghcr.io/panbartosz/kb-suite-app:latest
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - kb_suite_data:/app/data

volumes:
  kb_suite_data:
    external: true
